#!/bin/bash

export DATASHEET_PATH='/local/datasheets/msp430/'
export GCC_EXTRA_INC_DIR='/opt/msp430-gcc-support-files/include'

export GOOD=$'\e[32;01m'
export WARN=$'\e[33;01m'
export BAD=$'\e[31;01m'
export HILITE=$'\e[36;01m'
export BRACKET=$'\e[34;01m'
export NORMAL=$'\e[0m'

err()
{
    >&2 echo "$@"; 
}

# convert 'msp430f5510' to '__MSP430F5510__'
convert_name_to_target()
{
    echo "__$(echo "${1}" | tr '[:lower:]' '[:upper:]')__"
}

# convert '__MSP430F5510__' to 'msp430f5510'
convert_target_to_name()
{
    echo "${1}" | sed 's|_||g' | tr '[:upper:]' '[:lower:]'
}

# function thet uses two algorithms to guess the family name based on a target string
# the best guess is sent to stdout
guess_family_from_target()
{
    target=$1
    header=$(grep -A1 "${target}" "${GCC_EXTRA_INC_DIR}/msp430.h" | grep '#include' | sed 's|.*include[ ]"\(.*\)".*|\1|')
    unset FAMILY_N
    unset FAMILY_S
    unset FAMILY_H
    unset FAMILY
    
    [ ! -e "${GCC_EXTRA_INC_DIR}/${header}" ] && {
        err "header ${header} is missing"
        return 1
    }
    
    # try to guess the family based on the target name
    echo "${target}" | grep -q 'CC430F5' && local FAMILY_N=MSP430F5xx_6xx
    echo "${target}" | grep -q 'MSP430F5' && local FAMILY_N=MSP430F5xx_6xx
    echo "${target}" | grep -q 'MSP430F6' && local FAMILY_N=MSP430F5xx_6xx
    echo "${target}" | grep -q 'MSP430FR2' && local FAMILY_N=MSP430FR2xx_4xx
    echo "${target}" | grep -q 'MSP430FR4' && local FAMILY_N=MSP430FR2xx_4xx
    echo "${target}" | grep -q 'MSP430FR5' && local FAMILY_N=MSP430FR5xx_6xx
    echo "${target}" | grep -q 'MSP430FR57' && local FAMILY_N=MSP430FR57xx
    echo "${target}" | grep -q 'MSP430FR6' && local FAMILY_N=MSP430FR5xx_6xx
    
    # try to get family name from the header
    FAMILY_S=$(grep '^#define.*FAMILY__' "${GCC_EXTRA_INC_DIR}/${header}" | strings)

    if [ -n "${FAMILY_S}" ]; then
        echo "${FAMILY_S}" | grep -q '__MSP430F5XX_6XX_FAMILY__' && local FAMILY_H=MSP430F5xx_6xx
        echo "${FAMILY_S}" | grep -q '__MSP430FR2XX_4XX_FAMILY__' && local FAMILY_H=MSP430FR2xx_4xx
        echo "${FAMILY_S}" | grep -q '__MSP430FR57XX_FAMILY__' && local FAMILY_H=MSP430FR57xx
        echo "${FAMILY_S}" | grep -q '__MSP430FR5XX_6XX_FAMILY__' && local FAMILY_H=MSP430FR5xx_6xx
    fi

    if [ -z "${FAMILY_N}" ] && [ -z "${FAMILY_H}" ]; then 
        return 0
    fi

    if [ "${FAMILY_N}" != "${FAMILY_H}" ]; then
        if [ -z "${FAMILY_N}" ]; then
            local FAMILY="${FAMILY_H}"
        else
            err "err family mismatch FAMILY_N = ${FAMILY_N}, FAMILY_H = ${FAMILY_H}"
        fi
    else
        FAMILY="${FAMILY_H}"
    fi

    echo "${FAMILY}"
}

# function thet uses two algorithms to guess the family name based on chip name
# the best guess is sent to stdout
guess_family_from_name()
{
    target=$(convert_name_to_target "${1}")
    guess_family_from_target "${target}"
}

# function that combines multiple bitwise operations on the same register with a single operation
# in C files generated by an earlier stage of this tool
# $1 - input source file
# $2 - output source file
bitwise_comb()
{
    input="${1}"
    output="${2}"

    true > "${output}" || {
        err "error: cannot write to output file, exiting"
        return 1
    }

    cat "${input}" | while read -r line; do
        if echo "${line}" | grep -q 'P[0-9JSELDIR]* &= .*'; then
            register=$(echo "${line}" | grep -o 'P[0-9JSELDIR]*')
            #search for the same register with the same operator
            register_comb=$(grep "${register} &=" "${input}")
            register_comb_lncnt=$(echo "${register_comb}" | wc -l)
            if [ "${register_comb_lncnt}" == "2" ]; then
                #extract values
                values=$(echo "${register_comb}" | awk '{ print $3 }' | sed 's|;||g' | sort -n | xargs)
                negations_cnt=$(echo "${values}" | tr -d -c '~' | wc -c)
                if [ "${negations_cnt}" == "2" ]; then
                    new_value=$(echo "${values}" | sed 's|~||g;s|[ ]| \| |')
                    new_line="    ${register} &= ~(${new_value});"
                    grep -q "^${new_line}$" "${output}" || 
                        echo "${new_line}" >> "${output}"
                else
                    echo "${line}" >> "${output}"
                fi
                #echo ${values}
            else
                echo "${line}" >> "${output}"
            fi
        elif echo "${line}" | grep -q 'P[0-9SELDIR]* |= .*'; then
            register=$(echo "${line}" | grep -o 'P[0-9JSELDIR]*')
            #search for the same register with the same operator
            register_comb=$(grep "${register} |=" "${input}")
            register_comb_lncnt=$(echo "${register_comb}" | wc -l)
            if [ "${register_comb_lncnt}" == "2" ]; then
                #extract values
                values=$(echo "${register_comb}" | awk '{ print $3 }' | sed 's|;||g' | sort -n | xargs)
                negations_cnt=$(echo "${values}" | tr -d -c '~' | wc -c)
                if [ "${negations_cnt}" == "0" ]; then
                    new_value=$(echo "${values}" | sed 's|[ ]| \| |')
                    new_line="    ${register} |= ${new_value};"
                    grep -q "^${new_line}$" "${output}" || 
                        echo "${new_line}" >> "${output}"
                else
                    echo "${line}" >> "${output}"
                fi
                #echo ${values}
            else
                echo "${line}" >> "${output}"
            fi

        else
            # line not recognized, output as is
            echo "${line}"
        fi
    done
}


# function that combines separate source files (one for each microcontroller) into one 
# C source file that contains ifdefs
ifdef_comb()
{
    hash_file="${1}"
    unique_hashes=$(awk '{ print $1 }' "${hash_file}" | sort -u)

    first_ifdef_in_file=true
    for hash in ${unique_hashes}; do
        unset ifdef_line
        sources=$(grep "${hash}" "${hash_file}" | awk '{ print $2 }')
        first_ifdef_in_line=true
        for source in ${sources}; do
            uc_name=$(basename "${source}" | sed 's|\(.\)_.*|\1|')
            target=$(convert_name_to_target "${uc_name}")
            if ${first_ifdef_in_file}; then
                def_cnt=1
                echo -n "#if defined (${target})"
                first_ifdef_in_file=false
                first_ifdef_in_line=false
            else
                if ${first_ifdef_in_line}; then
                    def_cnt=1
                    echo -n "#elif defined (${target})"
                    first_ifdef_in_line=false
                else
                    [ "${def_cnt}" -gt 1 ] && {
                        echo ' \' >> "${output_file}"
                        def_cnt=0
                    }
                    echo -n " || defined (${target})"
                    ((def_cnt+=1))
                fi
            fi
        done
        echo ''
        cat "${source}"
    done
}

