#ifndef __GLUE_FS_H__
#define __GLUE_FS_H__

#include "msp430_hal.h"
#include "clock_selection.h"
#include "clock.h"
#include "clock_pin.h"
#include "uart_config.h"
#include "uart_uca0_pin.h"
#include "uart_uca1_pin.h"
#include "uart_uca2_pin.h"
#include "uart_uca3_pin.h"
#include "i2c_ucb0_pin.h"
#include "i2c_ucb1_pin.h"
#include "i2c_ucb2_pin.h"
#include "i2c_ucb3_pin.h"
#include "i2c_pin.h"
#include "spi_uca0_pin.h"
#include "spi_uca1_pin.h"
#include "spi_uca2_pin.h"
#include "spi_uca3_pin.h"
#include "spi_ucb0_pin.h"
#include "spi_ucb1_pin.h"
#include "spi_ucb2_pin.h"
#include "spi_ucb3_pin.h"
#include "spi_pin.h"
#include "spi_cs_uca0_pin.h"
#include "spi_cs_uca1_pin.h"
#include "spi_cs_uca2_pin.h"
#include "spi_cs_uca3_pin.h"
#include "spi_cs_ucb0_pin.h"
#include "spi_cs_ucb1_pin.h"
#include "spi_cs_ucb2_pin.h"
#include "spi_cs_ucb3_pin.h"
#include "spi_cs_pin.h

#endif
